using FanslationStudio.LlmKit;
using Translate;
using System.IO.Compression;

namespace Tests;

public class FileOutputWorkflowTests
{
    [Fact(DisplayName = "6. Package to Game Files")]
    public static async Task PackageFinalTranslation()
    {
        await TranslationPackaging.PackageFinalTranslationAsync(GameFileHandling.WorkingDirectory, TextFileConfiguration.TextFilesToSplit);

        var sourceDirectory = $"{GameFileHandling.WorkingDirectory}/Mod/";

        // "Mods/English", not a flat "Mods/" - matches this game's own native mod-loading
        // convention (FunctionalPlugin_Binarizer's ModSupport scans "Mods/<language>/", confirmed
        // live via its own log line "ModSupport: Scan mod path .../Mods/English") and, more
        // importantly, matches what LegendOfMortalPlugin/StringTableInjectionPatches.cs's GetString redirect
        // reads at runtime (Mods/English/*.csv) - copying to a flat Mods/ here would silently
        // leave the plugin's translation dictionary empty.
        var modDirectory = $"{GameFileHandling.GameFolder}/Mods/English/";

        if (Directory.Exists(modDirectory))
            Directory.Delete(modDirectory, true);

        GameFileHandlingBase.CopyDirectory(sourceDirectory, modDirectory);
    }

    [Fact(DisplayName = "7. Zip Release")]
    public static async Task ZipRelease()
    {
        var version = GameFileHandlingBase.CalculateVersionNumber();
        var workingDirectory = GameFileHandling.WorkingDirectory;

        string releaseFolder = $"{GameFileHandling.GameFolder}/ReleaseFolder/Files";

        // "Mods/English", not a flat "Mods/" - see the matching comment in PackageFinalTranslation above.
        GameFileHandlingBase.CopyDirectory($"{workingDirectory}/Mod", $"{releaseFolder}/Mods/English", true);

        //File.Copy($"{workingDirectory}/Autotranslator/_AutoGeneratedTranslations.txt", $"{releaseFolder}/BepInEx/Translation/en/Text/_AutoGeneratedTranslations.txt", true);
        //File.Copy($"{workingDirectory}/Autotranslator/_Postprocessors.txt", $"{releaseFolder}/BepInEx/Translation/en/Text/_Postprocessors.txt", true);
        //File.Copy($"{workingDirectory}/Autotranslator/_Preprocessors.txt", $"{releaseFolder}/BepInEx/Translation/en/Text/_Preprocessors.txt", true);
        //File.Copy($"{workingDirectory}/Autotranslator/_Substitutions.txt", $"{releaseFolder}/BepInEx/Translation/en/Text/_Substitutions.txt", true);
        //File.Copy($"{workingDirectory}/Autotranslator/mainmenu.resizer.txt", $"{releaseFolder}/BepInEx/Translation/en/Text/mainmenu.resizer.txt", true);
        //File.Copy($"{workingDirectory}/Autotranslator/status.resizer.txt", $"{releaseFolder}/BepInEx/Translation/en/Text/status.resizer.txt", true);
        //File.Copy($"{workingDirectory}/Autotranslator/story.resizer.txt", $"{releaseFolder}/BepInEx/Translation/en/Text/story.resizer.txt", true);

        GameFileHandlingBase.CopyDirectory($"{workingDirectory}/Resizers", $"{releaseFolder}/BepInEx/resizers", true);

        ZipFile.CreateFromDirectory($"{releaseFolder}", $"{releaseFolder}/../EnglishPatch-{version}.zip");
        await Task.CompletedTask;
    }
}
