using System.IO.Compression;
using Translate.Utility;
using static SweetPotato.FileView;

namespace Translate.Tests;

public class FileOutputWorkflowTests
{
    public const string WorkingDirectory = TranslationWorkflowTests.WorkingDirectory;
    public const string GameFolder = TranslationWorkflowTests.GameFolder;


    [Fact(DisplayName = "6. Package to Game Files")]
    public static async Task PackageFinalTranslation()
    {
        await FileOutputHandling.PackageFinalTranslationAsync(WorkingDirectory);

        var sourceDirectory = $"{WorkingDirectory}/Mod/";
        var modDirectory = $"{GameFolder}/Mods/";

        if (Directory.Exists(modDirectory))
            Directory.Delete(modDirectory, true);

        FileOutputHandling.CopyDirectory(sourceDirectory, modDirectory);
    }

    [Fact(DisplayName = "7. Zip Release")]
    public static async Task ZipRelease()
    {
        var version = ModHelper.CalculateVersionNumber();

        string releaseFolder = $"{GameFolder}/ReleaseFolder/Files";

        File.Copy($"{WorkingDirectory}/Mod/English/StringTable.csv", $"{releaseFolder}/Mods/English/StringTable.csv", true);

        File.Copy($"{WorkingDirectory}/Autotranslator/_AutoGeneratedTranslations.txt", $"{releaseFolder}/BepInEx/Translation/en/Text/_AutoGeneratedTranslations.txt", true);
        File.Copy($"{WorkingDirectory}/Autotranslator/_Postprocessors.txt", $"{releaseFolder}/BepInEx/Translation/en/Text/_Postprocessors.txt", true);
        File.Copy($"{WorkingDirectory}/Autotranslator/_Preprocessors.txt", $"{releaseFolder}/BepInEx/Translation/en/Text/_Preprocessors.txt", true);
        File.Copy($"{WorkingDirectory}/Autotranslator/_Substitutions.txt", $"{releaseFolder}/BepInEx/Translation/en/Text/_Substitutions.txt", true);
        File.Copy($"{WorkingDirectory}/Autotranslator/mainmenu.resizer.txt", $"{releaseFolder}/BepInEx/Translation/en/Text/mainmenu.resizer.txt", true);
        File.Copy($"{WorkingDirectory}/Autotranslator/status.resizer.txt", $"{releaseFolder}/BepInEx/Translation/en/Text/status.resizer.txt", true);
        File.Copy($"{WorkingDirectory}/Autotranslator/story.resizer.txt", $"{releaseFolder}/BepInEx/Translation/en/Text/story.resizer.txt", true);


        FileOutputHandling.CopyDirectory($"{WorkingDirectory}/Resizers", $"{releaseFolder}/BepInEx/resizers", true);

        ZipFile.CreateFromDirectory($"{releaseFolder}", $"{releaseFolder}/../EnglishPatch-{version}.zip");
        await Task.CompletedTask;
    }
}
