using FanslationStudio.LlmKit;
using System.IO.Compression;

namespace Translate.Tests;

public class FileOutputWorkflowTests
{
    [Fact(DisplayName = "6. Package to Game Files")]
    public static async Task PackageFinalTranslation()
    {
        await TranslationPackaging.PackageFinalTranslationAsync(GameFileHandling.WorkingDirectory, TextFileConfiguration.TextFilesToSplit);

        var sourceDirectory = $"{GameFileHandling.WorkingDirectory}/Mod/";
        var modDirectory = $"{GameFileHandling.GameFolder}/Mods/";

        if (Directory.Exists(modDirectory))
            Directory.Delete(modDirectory, true);

        GameFileHandlingBase.CopyDirectory(sourceDirectory, modDirectory);
    }

    [Fact(DisplayName = "7. Zip Release")]
    public static async Task ZipRelease()
    {
        var version = GameFileHandlingBase.CalculateVersionNumber();
        var workingDirectory = GameFileHandling.WorkingDirectory;

        string releaseFolder = $"{GameFileHandling.GameFolder}/ReleaseFolder/Files";

        GameFileHandlingBase.CopyDirectory($"{workingDirectory}/Mod", $"{releaseFolder}/Mods", true);

        File.Copy($"{workingDirectory}/Autotranslator/_AutoGeneratedTranslations.txt", $"{releaseFolder}/BepInEx/Translation/en/Text/_AutoGeneratedTranslations.txt", true);
        File.Copy($"{workingDirectory}/Autotranslator/_Postprocessors.txt", $"{releaseFolder}/BepInEx/Translation/en/Text/_Postprocessors.txt", true);
        File.Copy($"{workingDirectory}/Autotranslator/_Preprocessors.txt", $"{releaseFolder}/BepInEx/Translation/en/Text/_Preprocessors.txt", true);
        File.Copy($"{workingDirectory}/Autotranslator/_Substitutions.txt", $"{releaseFolder}/BepInEx/Translation/en/Text/_Substitutions.txt", true);
        File.Copy($"{workingDirectory}/Autotranslator/mainmenu.resizer.txt", $"{releaseFolder}/BepInEx/Translation/en/Text/mainmenu.resizer.txt", true);
        File.Copy($"{workingDirectory}/Autotranslator/status.resizer.txt", $"{releaseFolder}/BepInEx/Translation/en/Text/status.resizer.txt", true);
        File.Copy($"{workingDirectory}/Autotranslator/story.resizer.txt", $"{releaseFolder}/BepInEx/Translation/en/Text/story.resizer.txt", true);

        GameFileHandlingBase.CopyDirectory($"{workingDirectory}/Resizers", $"{releaseFolder}/BepInEx/resizers", true);

        ZipFile.CreateFromDirectory($"{releaseFolder}", $"{releaseFolder}/../EnglishPatch-{version}.zip");
        await Task.CompletedTask;
    }
}
